GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order pizza"
}

###

DELETE http://localhost:3001/todo/delete/653346682cf433a109851a46

###
PUT http://localhost:3001/todo/complete/653345d72cf433a109851a43